
###PREFIXXXX = /home/james/code/evanescent/play/makefile/

TOOL = rm -i

all:
	echo prefix is: $(PREFIX)

test:
	#touch $(PREFIX)somefile
	#mkdir $(PREFIX)somedir
	#touch $(PREFIX)somedir/someotherfile
	$(TOOL) $(PREFIX)somefile
	#$(TOOL) -r $(PREFIX)somedir

